<h3 style="margin: 13pt 0cm; text-align: center; line-height: 36.9067px; break-after: avoid; font-size: 16pt; font-family: Calibri, 'sans-serif';" align="center"><span style="font-size: 18pt; line-height: 41.52px; font-family: 宋体;">锋源网络国际网络加速服务信息安全承诺书</span></h3>
<p class="MsoNormal" style="margin: 0cm 0cm 0.0001pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; text-indent: 1cm; line-height: 19.6px;" align="left"><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">本单位<span lang="EN-US">/</span>个人对于所使用的锋源网络国际网络加速业务（包括但不限于国际专线<span lang="EN-US">IPLC</span>、国际以太网专线<span lang="EN-US">IEPL</span>、<span lang="EN-US">IP VPN</span>等），明确企业主体<span lang="EN-US">/</span>个人主体责任和法律责任，向锋源网络不可撤销地承诺如下：</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">一.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;</span></span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">本单位<span lang="EN-US">/</span>个人承诺遵守中华人民共和国大陆地区以及国际网络所经国家和地区的有关法律、行政法规和管理规章，严格执行信息安全管理规定。</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">二.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;</span></span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">本单位接受锋源网络及国家相关部门的管理、监督和检查，有责任和义务积极配合锋源网络查找、清除非法网络行为，直至处理完毕。</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">三.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;</span></span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">本单位<span lang="EN-US">/</span>个人承诺规范使用锋源网络所提供的国际网络加速业务，使用用途为<u><span lang="EN-US">&nbsp;&nbsp;&nbsp;</span>自用<span lang="EN-US">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></u>。该业务不得用于连接境内外数据中心或业务平台开展电信业务经营活动，不违规经营，不转租转售。如有转租转售等违规行为，锋源网络有权单方终止与本单位<span lang="EN-US">/</span>个人的网络加速服务并注销其账号，而不必承担责任，由此给锋源网络成任何损失的，本单位承担赔偿责任。</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">四.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;</span></span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">本单位<span lang="EN-US">/</span>个人承诺不通过电信网络制作、复制、发布、传播含有下列内容的信息：网络制作、复制、查阅和传播下列信息：</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21.25pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">1</span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">．反对宪法所确定的基本原则的；</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21.25pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">2</span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">．危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21.25pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">3.&nbsp;</span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">损害国家荣誉和利益的；</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21.25pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">4</span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">．煽动民族仇恨、民族歧视，破坏民族团结的；</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21.25pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">5</span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">．破坏国家宗教政策，宣扬邪教和封建迷信的；</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21.25pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">6</span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">．散布谣言，扰乱社会秩序，破坏社会稳定的；</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21.25pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">7</span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">．散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的；</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21.25pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">8.&nbsp;</span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">侮辱或者诽谤他人，侵害他人合法权益的；</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21.25pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">9.&nbsp;</span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">含有法律、行政法规禁止的其他内容的。</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 21pt; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">五.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;</span></span><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">本单位<span lang="EN-US">/</span>个人承诺如违反本承诺书所列任何一项条款，由本单位<span lang="EN-US">/</span>个人直接承担相应法律责任，并接受相关管理部门的严肃处理，造成本单位自身财产损失或造成其他方财产损失的，由本单位<span lang="EN-US">/</span>个人直接赔偿。同时，锋源网络有权单方暂停提供网络加速服务或者注销其账号，而不必承担任何责任，如果由此给锋源网络造成任何损失的，本单<span lang="EN-US">/</span>个人位将承担锋源网络方损失。</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt 21pt; text-indent: 0cm; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 19.6px;" align="left"><span style="font-size: 12pt; line-height: 22.4px; font-family: 仿宋_GB2312;">本承诺书自账号注册日起生效并遵行。</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt -7.05pt; text-indent: 0cm; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 18.2px;" align="left"><span lang="EN-US" style="font-size: 12pt; line-height: 20.8px; font-family: 仿宋_GB2312;">&nbsp;</span></p>
<p class="MsoListParagraph" style="margin: 0cm 0cm 0.0001pt; text-indent: 0cm; font-size: 10.5pt; font-family: Calibri, 'sans-serif'; line-height: 18.2px;" align="left"><span style="font-size: 12pt; line-height: 20.8px; font-family: 仿宋_GB2312;">特此承诺。</span></p>