<title>锋源网络隐私政策</title>
<p style="text-align: center; line-height: 20.25pt; mso-pagination: widow-orphan; background: white;" align="center"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 13.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;"><span style="mso-spacerun: yes;">&nbsp; </span></span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 13.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">隐私权政策</span></strong></p>
<p style="text-align: center; text-indent: 21.0pt; line-height: 20.25pt; mso-pagination: widow-orphan; background: white;" align="center"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 13.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">前言</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">锋源网络一向庄严承诺保护使用锋源网络的产品和服务之用户</span><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">（以下统称&ldquo;用户&rdquo;或&ldquo;您&rdquo;）</span></u></strong><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">的隐私。您在使用锋源网络服务时，我们可能会收集和使用您的相关信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">本《隐私政策》适用于我们提供的一切锋源网络服务。当您使用我们任何单项服务时，您同意接受本《隐私政策》以及我们在该单项服务中发出的特定隐私信息类政策条款（下列称&ldquo;特定条款&rdquo;）的保护，在此情况下特定条款与本政策条款同时对您产生效力。例如：使用锋源网络在线服务的用户，同时适用本《隐私政策》以及《网络游戏用户隐私权保护和个人信息利用政策》（见附件一）；又如，使用锋源网络支付的用户，同时适用本《隐私政策》以及《锋源网络支付隐私政策》（见附件二）。如特定条款与本《隐私政策》条款存在同类条款的不一致约定，则在特定条款约束范围内应以特定条款为准。如我们提供的某一单项服务不适用本《隐私政策》的，该服务中会以适当方式明示排除适用本《隐私政策》。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">请注意我们不时地会检查我们的政策，因此有关的措施会随之变化。我们恳请您定期光顾本页面，以确保对我们《隐私政策》最新版本始终保持了解</span></u></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">您使用或继续使用锋源网络服务，都表示您同意我们按照本《隐私政策》收集、使用、储存和分享您的信息。</span></u></strong><u></u></p>
<p style="text-align: center; text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;" align="center"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">目录</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">一、我们可能收集的信息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">二、我们如何收集和使用信息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">三、我们可能分享、转让和披露的信息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">四、我们如何保留、储存和保护信息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">五、如何管理您的信息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">六、第三方服务</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">七、年龄限制</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">八、通知和修订</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">九、如何联系我们</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">一、我们可能收集的信息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（一）与个人身份无关的信息：</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">当您使用锋源网络服务时，我们可能收集和汇总诸如用户的来源途径、访问顺序等信息，例如记录使用锋源网络服务的每个用户的来源途径、浏览器软件等。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（二）有关个人身份的信息：</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">当您使用锋源网络服务时，我们可能收集和汇总或要求您提供有关个人身份的信息，例如个人身份证明（包括身份证、护照、驾驶证等）；生日、籍贯、性别、兴趣爱好、个人电话号码、面部特征；网络身份标识信息（包括系统账号、<span lang="EN-US">IP</span>地址、电子邮箱地址及与前述有关的密码、口令、口令保护答案等）；个人财产信息（交易记录、余额、优惠券、游戏类兑换码、银行卡信息等）；通讯信息；个人上网记录和日志信息（包括网站浏览记录、软件使用记录、点击记录、操作日志等）；设备信息（包括设备型号、设备<span lang="EN-US">MAC</span>地址、操作系统类型、设备设置）；软件列表唯一设备识别码（如<span lang="EN-US">IMEI/android ID/IDFA/OPENUDID/GUID</span>、<span lang="EN-US">SIM</span>卡<span lang="EN-US">IMSI</span>信息等在内的描述个人常用设备基本情况的信息）；位置信息（包括行程信息、精准定位信息、住宿信息、经纬度等）。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们收集您的信息主要是为了您和其他用户能够更容易和更满意地使用锋源网络服务。锋源网络的目标是向所有的互联网用户提供安全、刺激、有趣及有教益的上网经历。而这些信息有助于我们实现这一目标。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">请注意，如您在锋源网络服务中其他用户可见的公开区域内上传或发布的信息中、您对其他人上传或发布的信息作出的回应中公开您的个人信息，该等信息可能会被他人收集并加以使用。当您发现锋源网络的用户不正当地收集或使用您或他人的信息时，请联系我们</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">二、我们如何收集和使用信息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（一）我们将通过以下途径收集和获得您的信息：</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">1</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、您提供的信息。</span></strong><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">例如：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">1</span>）您在注册锋源网络服务的帐号或使用服务时，向我们提供的信息；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">2</span>）您通过锋源网络服务向其他方提供的共享信息，以及您使用锋源网络服务时所储存的信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">2</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、其他方分享的您的信息。</span></strong><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">亦即其他方使用锋源网络服务时所提供有关您的共享信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">3</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、我们获取的您的信息。</span></strong><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">您在使用锋源网络服务时，我们收集、汇总、记录的信息，例如日志信息、位置信息、设备信息等。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（二）我们会出于以下目的，收集和使用您的信息：</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">1</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、帮助您完成注册</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">为便于我们为您提供服务，您需要提供基本注册信息，例如手机号码、电子邮箱地址等，并创建您的用户名和密码。在部分单项服务中，如果您仅需使用浏览、搜索等基本服务，您不需要注册成为锋源网络用户及提供上述信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">2</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、向您提供商品或服务</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们所收集和使用的信息是为您提供锋源网络服务的必要条件，如缺少相关信息，我们将无法为您提供锋源网络服务的核心内容，例如：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">1</span>）在部分服务项目中，为便于向您交付商品或服务，您需提供收货人个人身份信息、姓名、收货地址、邮政编码、收货人、联系电话、支付状态等信息。如果您拒绝提供此类信息，我们将无法完成相关交付服务。如您通过锋源网络服务为其他人订购商品或服务，您需要提供该实际订购人的前述信息。</span><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">向我们提供该实际订购人的前述信息之前，您需确保您已经取得其授权同意。</span></u></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">2</span>）为展示您账户的订单信息，我们会收集您在使用锋源网络服务过程中产生的订单信息用于向您展示及便于您对订单进行管理；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">3</span>）当您与我们联系时，我们可能会保存您的通信<span lang="EN-US">/</span>通话记录和内容或您留下的联系方式等信息，以便与您联系或帮助您解决问题，或记录相关问题的处理方案及结果。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">4</span>）为确认交易状态及为您提供售后与争议解决服务，我们会通过您基于交易所选择的交易对象、支付机构、物流公司等收集与交易进度相关的您的交易、支付、物流信息，或将您的交易信息共享给上述服务提供者。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">3</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、向您推送消息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">为您展示和推送商品或服务。我们可能使用您的信息，您的浏览及搜索记录、设备信息、位置信息、订单信息，提取您的浏览、搜索偏好、行为习惯、位置信息等特征，并基于特征标签通过电子邮件、短信或其他方式向您发送营销信息，提供或推广我们或第三方的如下商品和服务：</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们的商品和服务，包括但不限于：即时通讯服务、网上媒体服务、互动娱乐服务、社交网络服务、支付服务、互联网搜索服务、位置和地图服务、应用软件和服务、数据管理软件和服务、网上广告服务、互联网金融及其他社交媒体、娱乐、网络游戏、电子商务、资讯及通讯软件和服务（&ldquo;互联网服务&rdquo;）；及</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">第三方商品和服务，包括但不限于：互联网服务、食物和餐饮、体育、音乐、电影、电视、现场表演和其他艺术和娱乐、书册、杂志和其他刊物、服装和配饰、珠宝、化妆品、个人健康和卫生、电子、收藏品、家用器皿、电器、家居装饰和摆设、宠物、汽车、酒店、交通和旅游、银行、保险及金融服务、积分和奖励计划，以及我们认为可能与您相关的其他商品和服务。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">4</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、改进我们的服务</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们可能将通过某一项锋源网络服务所收集的信息，用于我们的其他服务。例如，在您使用某一项锋源网络服务时所收集的您的信息，可能在另一项锋源网络服务中用于向您提供特定内容或向您展示与您相关的、而非普遍推送的信息；我们可能让您参与有关锋源网络服务的调查，帮助我们改善现有服务或设计新服务；同时，我们可能将您的信息用于软件更新。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">您了解并同意，在收集您的信息后，我们将通过技术手段对数据进行去标识化处理，去标识化处理的信息将无法识别您的身份，在此情况下我们有权使用已经去标识化的信息，对用户数据库进行分析并予以商业化的利用。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">如果我们将您的信息用于本《隐私政策》中未载明的其他用途，会事先征求您同意。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">6</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、征得授权同意的例外</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">根据相关法律法规规定，以下情形中收集您的信息无需征得您的授权同意：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">1</span>）与国家安全、国防安全有关的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">2</span>）与公共安全、公共卫生、重大公共利益有关的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">3</span>）与犯罪侦查、起诉、审判和判决执行等有关的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">4</span>）出于维护信息主体或其他个人的生命、财产等重大合法权益但又很难得到您本人同意的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">5</span>）所收集的信息是您自行向社会公众公开的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">6</span>）从合法公开披露的信息中收集信息的，如合法的新闻报道、政府信息公开等渠道；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">7</span>）根据您的要求签订合同所必需的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">8</span>）用于维护锋源网络服务的安全稳定运行所必需的，例如发现、处置产品或服务的故障；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">9</span>）为合法的新闻报道所必需的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">10</span>）学术研究机构基于公共利益开展统计或学术研究所必要，且对外提供学术研究或描述的结果时，对结果中所包含的信息进行去标识化处理的；（<span lang="EN-US">11</span>）法律法规规定的其他情形。</span></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">三、我们可能分享、转让或披露的信息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（一）分享</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">除以下情形外，未经您同意，我们不会与锋源网络之外的任何第三方分享您的信息：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">1</span></u></strong><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">、向您提供我们的服务。我们可能向合作伙伴及其他第三方分享您的信息，以实现您需要的核心功能或提供您需要的服务，例如：向物流服务商提供对应的订单信息；</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">2</span></u></strong><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">、维护和改善我们的服务。我们可能向合作伙伴及其他第三方分享您的信息，以帮助我们为您提供更有针对性、更完善的服务，例如：代表我们发出电子邮件或推送通知的通讯服务提供商等；</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">3</span></u></strong><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">、实现本《隐私政策》第二条&ldquo;我们如何收集和使用信息&rdquo;部分所述目的；</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">4</span></u></strong><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">、履行我们在本《隐私政策》或我们与您达成的其他协议中的义务和行使我们的权利；</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">5</span></u></strong><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">、向委托我们进行推广的合作伙伴等第三方共享，但我们仅会向这些委托方提供推广的覆盖面和有效性的信息，而不会提供可以识别您身份的信息，例如姓名电话号码或电子邮箱；或者我们将这些信息进行汇总，以便它不会识别您个人。比如我们可以告知该委托方有多少人看了他们的推广信息或在看到这些信息后购买了委托方的商品，或者向他们提供不能识别个人身份的统计信息，帮助他们了解其受众或顾客。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">6</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、在法律法规允许的范围内，为了遵守法律、维护我们及我们的关联方或合作伙伴、您或其他锋源网络用户或社会公众利益、财产或安全免遭损害，比如为防止欺诈等违法活动和减少信用风险，我们可能与其他公司和组织交换信息。不过<span lang="EN-US">,</span>这并不包括违反本《隐私政策》中所作的承诺而为获利目的出售、出租、共享或以其它方式披露的信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">7</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、应您合法需求，协助处理您与他人的纠纷或争议；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">8</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、应您的监护人合法要求而提供您的信息；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">9</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、根据与您签署的单项服务协议（包括在线签署的电子协议以及相应的平台规则）或其他的法律文件约定所提供；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">10</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、基于学术研究而提供；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">11</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、基于符合法律法规的社会公共利益而提供。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们仅会出于合法、正当、必要、特定、明确的目的共享您的信息。对我们与之共享信息的公司、组织和个人，我们会与其签署严格的保密协定，要求他们按照我们的说明、本《隐私政策》以及其他任何相关的保密和安全措施来处理信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（二）转让</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">1</span></u></strong><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">、随着我们业务的持续发展，我们有可能进行合并、收购、资产转让或类似的交易，而您的信息有可能作为此类交易的一部分而被转移。</span></u></strong><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们会要求新的持有您信息的公司、组织继续受本《隐私政策》的约束，否则<span lang="EN-US">,</span>我们将要求该公司、组织重新向您征求授权同意。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">2</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、在获得您的明确同意后，我们会向其他方转让您的信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（三）披露</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们仅会在以下情况下，且采取符合业界标准的安全防护措施的前提下，才会披露您的信息：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">1</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、根据您的需求，在您明确同意的披露方式下披露您所指定的信息；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">2</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、根据法律、法规的要求、强制性的行政执法或司法要求所必须提供您信息的情况下，我们可能会依据所要求的信息类型和披露方式披露您的信息。在符合法律法规的前提下，当我们收到上述披露信息的请求时，我们会要求接收方必须出具与之相应的法律文件，如传票或调查函。我们坚信，对于要求我们提供的信息，应该在法律允许的范围内尽可能保持透明。我们对所有的请求都进行了慎重的审查，以确保其具备合法依据，且仅限于执法部门因特定调查目的且有合法权利获取的数据。</span></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">四、我们如何保留、储存和保护信息</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们仅在本《隐私政策》所述目的所必需期间和法律法规要求的时限内保留您的信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们在中华人民共和国境内运营中收集和产生的信息，存储在中国境内，以下情形除外：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">1</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、法律法规有明确规定；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">2</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、获得您的授权同意；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">3</span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">、您使用的产品、服务涉及跨境，锋源网络需要向境外提供您的个人信息的。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">针对以上情形，我们会确保依据本政策及国家法律法规要求对您的个人信息提供足够的保护。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们为保护信息采取的其他安全措施</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们通过建立数据分类分级制度、数据安全管理规范、数据安全开发规范来管理规范信息的存储和使用。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们通过信息接触者保密协议、监控和审计机制来对数据进行全面安全控制。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">加强安全意识。我们还会举办安全和隐私保护培训课程，加强员工对于保护信息重要性的认识。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">我们仅允许有必要知晓这些信息的锋源网络员工、合作伙伴访问您的信息，并为此设置了严格的访问权限控制和监控机制。我们同时要求可能接触到您的信息的所有人员履行相应的保密义务。如果未能履行这些义务，可能会被追究法律责任或被中止与锋源网络的合作关系。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们会采取一切合理可行的措施，确保未收集无关的信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">互联网并非绝对安全的环境，而且电子邮件、即时通讯、社交软件或其他服务软件等与其他用户的交流方式无法确定是否完全加密，我们建议您使用此类工具时请使用复杂密码，并注意保护您的信息安全。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">互联网环境并非百分之百安全，我们将尽力确保或担保您发送给我们的任何信息的安全性。如果我们的物理、技术、或管理防护设施遭到破坏，导致信息被非授权访问、公开披露、篡改、或毁坏，导致您的合法权益受损，我们将承担相应的法律责任。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">安全事件处置</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">在通过锋源网络服务与第三方进行沟通或购买商品及服务时，您不可避免的要向交易对方或潜在的交易对方披露自己的信息，如联络方式或者邮政地址等。请您妥善保护自己的信息，仅在必要的情形下向他人提供。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">为应对信息泄露、损毁和丢失等可能出现的风险，我们制定了多项制度，明确安全事件、安全漏洞的分类分级标准及相应的处理流程。我们也为安全事件建立了专门的应急响应团队，按照安全事件处置规范要求，针对不同安全事件启动安全预案，进行止损、分析、定位、制定补救措施、联合相关部门进行溯源和打击。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">在不幸发生信息安全事件后，我们将按照法律法规的要求，及时向您告知：安全事件的基本情况和可能的影响、我们已采取或将要采取的处置措施、您可自主防范和降低风险的建议、对您的补救措施等。我们同时将及时将事件相关情况以邮件、信函、电话、推送通知等方式告知您，难以逐一告知信息主体时，我们会采取合理、有效的方式发布公告。同时，我们还将按照监管部门要求，主动上报信息安全事件的处置情况。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">请您理解，由于技术的限制以及风险防范的局限，即便我们已经尽量加强安全措施，也无法始终保证信息百分之百的安全。您需要了解，您接入锋源网络服务所用的系统和通讯网络，有可能因我们可控范围外的情况而发生问题。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">有关敏感信息的提示</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">某些信息因其特殊性可能被认为是敏感信息，例如您的种族、宗教、个人健康和医疗信息等，以及身份证明文件、个人生物识别信息、财产信息、行踪轨迹、未成年人的信息等。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">请注意，您在锋源网络服务中所提供、上传或发布的内容和信息（例如有关您社交活动的照片或信息），可能会泄露您的敏感信息。您需要谨慎地考虑，是否使用锋源网络服务披露您的敏感信息。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">您同意您的敏感信息按本《隐私政策》所述的目的和方式来处理。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">六、第三方服务</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">锋源网络服务可能链接至第三方提供的社交媒体或其他服务（包括网站或其他服务形式）。包括：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">1</span>）您可利用&ldquo;分享&rdquo;键将某些内容分享到锋源网络服务，或您可利用第三方服务登录锋源网络服务。这些功能可能会收集您的信息（包括您的日志信息），并可能在您的电脑装置<span lang="EN-US">COOKIES</span>，从而正常运行上述功能；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">2</span>）我们通过广告或我们服务的其他方式向您提供链接，使您可以接入第三方的服务或网站；及</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">3</span>）其他接入第三方服务的情形。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">该等第三方社交媒体或其他服务由相关的第三方负责运营。您使用该等第三方的社交媒体服务或其他服务（包括您向该等第三方提供的任何信息），须受第三方自己的服务条款及信息保护声明（而非本《隐私政策》）约束，您需要仔细阅读其条款。本《隐私政策》仅适用于我们所收集的任何信息，并不适用于任何第三方提供的服务或第三方的信息使用规则，而我们对任何第三方使用由您提供的信息不承担任何责任。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">七、年龄限制</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们建议：</span><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">任何未成年人参加网上活动应事先取得家长或其法定监护人（以下简称<span lang="EN-US">"</span>监护人<span lang="EN-US">"</span>）的同意。</span></u></strong><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们将根据国家相关法律法规的规定保护未成年人的相关信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">我们鼓励父母或监护人指导未成年人使用锋源网络服务。我们建议未成年人鼓励他们的父母或监护人阅读本《隐私政策》，并建议未成年人在提交信息之前寻求父母或监护人的同意和指导。</span></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">八、通知和修订</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">我们可能适时修改本《隐私政策》的条款，该等修改构成本《隐私政策》的一部分。对于重大变更，我们会提供更显著的通知，您可以选择停止使用锋源网络服务；在该种情况下，如您仍然继续使用锋源网络服务的，即表示同意受经修订的本《隐私政策》的约束。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">任何修改都会将您的满意度置于首位。我们鼓励您在每次使用锋源网络服务时都查阅我们的隐私政策。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">我们可能在必需时（例如当我们由于系统维护而暂停某一项服务时）发出与服务有关的公告。您可能无法取消这些与服务有关、性质不属于推广的公告。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">最后，您必须对您的账号和密码信息负有保密义务。任何情况下，请小心妥善保管。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 16.9pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 11.0pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">九、如何联系我们</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">如您有关于网络信息安全的投诉和举报，或您对本《隐私政策》、您的信息的相关事宜有任何问题、意见或建议，以及有关本声明或锋源网络的隐私措施的问题请与锋源网络的协调人联系。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">尽管有上述约定，但按照法律法规要求，在以下情形下，我们可能无法响应您的请求：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(1)</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">与国家安全、国防安全有关的；</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(2)</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">与公共安全、公共卫生、重大公共利益有关的；</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(3)</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">与犯罪侦查、起诉和审判等有关的；</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(4)</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">有充分证据表明您存在主观恶意或滥用权利的；</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(5)</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">响应您的请求将导致其他个人、组织的合法权益受到严重损害的。</span></strong></p>
<p class="MsoNormal" style="text-align: left; line-height: 150%;" align="left"><span lang="EN-US" style="font-family: 宋体; mso-ascii-theme-font: minor-fareast; mso-fareast-theme-font: minor-fareast; mso-hansi-theme-font: minor-fareast; mso-bidi-font-family: 宋体; mso-bidi-theme-font: minor-fareast;">&nbsp;</span></p>