<title>锋源网络用户协议</title>
<p style="line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">【注意】欢迎申请使用锋源网络提供的服务。</span></strong><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">请您（下列简称为&ldquo;用户&rdquo;）仔细阅读以下全部内容</span><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">（特别是粗体下划线标注的内容）</span></u></strong><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">。如用户不同意本服务条款任意内容，请勿注册或使用锋源网络服务。如用户通过进入注册程序并勾选&ldquo;我同意服务条款&rdquo;，即表示用户与锋源网络已达成协议，自愿接受本服务条款的所有内容。此后，用户不得以未阅读本服务条款内容作任何形式的抗辩。</span></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">1.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">服务条款的确认和接纳</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">锋源网络服务涉及到的产品的所有权以及相关软件的知识产权归锋源网络所有。锋源网络所提供的服务必须按照其发布的公司章程，服务条款和操作规则严格执行。本服务条款的效力范围及于将锋源网络手机帐号作为登录帐号的锋源网络产品和服务（以下简称&ldquo;锋源网络各单项服务&rdquo;），用户在享受锋源网络各单项服务时，应当受本服务条款的约束。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">当用户使用锋源网络各单项服务时，用户同意以单项服务要求的方式同意该单项服务的服务条款以及锋源网络在该单项服务中发出的各类公告（下列简称为&ldquo;单项条款&rdquo;），在此情况下单项条款与本服务条款同时对用户产生效力。若单项条款与本服务条款存在同类条款的冲突，则在单项条款约束范围内应以单项条款为准。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">2.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">锋源网络手机帐号服务简介</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">本服务条款所称的&ldquo;锋源网络手机帐号&rdquo;是指用户以手机号码作为帐号注册的合法、有效的帐号，锋源网络手机帐号注册成功后帐号即为手机号。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">锋源网络运用自己的操作系统通过国际互联网络为用户提供各项服务。用户必须：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">1</span>）提供设备，如个人电脑、手机或其他上网设备。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">2</span>）个人上网和支付与此服务有关的费用。</span></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">3.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">锋源网络手机帐号注册规则</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">锋源网络手机帐号注册资料包括但不限于：用户的手机号码、密码及注册锋源网络手机帐号或更新锋源网络手机帐号注册资料时输入的所有信息或更新手机帐号时输入的所有信息以及用户使用各单项服务时输入的名称、头像等所有信息。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">用户在注册锋源网络手机帐号时承诺遵守法律法规、社会主义制度、国家利益、公民合法权益、公共秩序、社会道德风尚和信息真实性等七条底线，不得在锋源网络手机帐号注册资料中出现违法和不良信息，且用户保证其在注册和使用帐号时，不得有以下情形：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">1</span>）违反宪法或法律法规规定的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">2</span>）危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">3</span>）损害国家荣誉和利益的，损害公共利益的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">4</span>）煽动民族仇恨、民族歧视，破坏民族团结的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">5</span>）破坏国家宗教政策，宣扬邪教和封建迷信的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">6</span>）散布谣言，扰乱社会秩序，破坏社会稳定的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">7</span>）散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">8</span>）侮辱或者诽谤他人，侵害他人合法权益的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">9</span>）含有法律、行政法规禁止的其他内容的。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">若用户提供给锋源网络的帐号注册资料不准确，不真实，含有违法或不良信息的，锋源网络有权不予注册，并保留终止用户使用锋源网络各项服务的权利。若用户以虚假信息骗取帐号注册或帐号头像、个人简介等注册资料存在违法和不良信息的，锋源网络有权采取通知限期改正、暂停使用、注销登记等措施。对于冒用关联机构或社会名人注册帐号名称的，锋源网络有权注销该帐号，并向政府主管部门进行报告。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">根据相关法律、法规规定以及考虑到锋源网络产品服务的重要性，用户同意：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">1</span>）在注册锋源网络手机帐号时提交个人有效身份信息进行实名认证；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">2</span>）提供及时、详尽及准确的帐户注册资料；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">3</span>）不断更新注册资料，符合及时、详尽准确的要求，对注册锋源网络手机帐号时填写的身份证件信息不能更新。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">用户同意，其提供的真实、准确、合法的锋源网络手机帐号注册资料作为认定用户与其锋源网络手机帐号的关联性以及用户身份的唯一证据。用户在享用锋源网络各项服务的同时，同意接受锋源网络提供的各类信息服务。锋源网络提醒用户，用户注册锋源网络手机帐号或更新注册信息时填写的证件号码，在注册锋源网络手机帐号成功或补充填写后将无法进行修改，请用户慎重填写各类注册信息。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">用户同意，在用户通过锋源网络公布的线上渠道或通过客服申诉并提交锋源网络要求的身份认证信息材料的，则该用户原锋源网络手机帐号下的所有使用记录及充值数据可以转移到该用户提供的，未注册过锋源网络手机帐号的新手机号关联的新锋源网络手机帐号并自行承担因此等转移可能产生的后果。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">为使用户及时、全面了解锋源网络提供的各项服务，用户同意，锋源网络可以多次、长期向用户发送各类商业性短信息而无需另行获得用户的同意。用户同意与注册、使用锋源网络手机帐号相关的一切资料、数据和记录，包括但不限于手机帐号、注册信息、所有登录、消费记录和相关的使用统计数字等归锋源网络所有。发生争议时，用户同意以锋源网络的系统数据为准，锋源网络保证该数据的真实性。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">尽管有前述约定，对于用户使用锋源网络手机帐号享受锋源网络旗下单项服务（如游戏产品、锋源网络支付产品等）时产生的一切数据，包括但不限于产品登录记录、消费记录及其他产品日志、产品客户服务记录、用户在产品中创造的社会网络内容等，归具体产品运营主体所有。发生争议时，用户同意以具体产品运营主体的系统数据为准。但是如果单项条款存在与前述不同的约定，则以单项条款约定为准。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">4.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">服务条款的修改</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">锋源网络有权在必要时通过在网页上发出公告等合理方式修改本服务条款以及各单项服务的相关条款。用户在享受各项服务时，应当及时查阅了解修改的内容，并自觉遵守本服务条款以及该单项服务的相关条款。用户如继续使用本服务条款涉及的服务，则视为对修改内容的同意，当发生有关争议时，以最新的服务条款为准；用户在不同意修改内容的情况下，有权停止使用本服务条款涉及的服务。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">5.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">服务的变更或中止</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">锋源网络始终在不断变更和改进服务。锋源网络可能会增加或删除功能，也可能暂停或彻底停止某项服务。用户同意锋源网络有权行使上述权利且不需对用户或第三方承担任何责任。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">6.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">用户隐私制度</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">尊重用户隐私是锋源网络的一项基本政策。锋源网络将按照锋源网络网站上公布的隐私政策，收集、存储、使用、披露和保护您的个人信息。请您完整阅读上述隐私权政策，以帮助您更好地保护您的个人信息。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">7.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">不可抗力条款</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">锋源网络对不可抗力导致的损失不承担责任。本服务条款所指不可抗力包括：天灾、法律法规或政府指令的变更，因网络服务特性而特有的原因，例如境内外基础电信运营商的故障、计算机或互联网相关技术缺陷、互联网覆盖范围限制、计算机病毒、黑客攻击等因素，及其他合法范围内的不能预见、不能避免并不能克服的客观情况。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">8.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">禁止服务的商业化</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">用户承诺，非经锋源网络同意，用户不能利用锋源网络各项服务进行销售或其他商业用途。如用户有需要将服务用于商业用途，应书面通知锋源网络并获得锋源网络的明确授权。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">9.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">用户管理</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">用户独立承担其发布内容的责任。用户对服务的使用必须遵守所有适用于服务的地方法律、国家法律和国际法律。用户承诺：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">1</span>）用户在锋源网络的网页上发布信息或者利用锋源网络的服务时必须符合中国有关法规，不得在锋源网络的网页上或者利用锋源网络的服务制作、复制、发布、传播以下信息：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(a) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">违反宪法确定的基本原则的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(b) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(c) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">损害国家荣誉和利益的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(d) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">煽动民族仇恨、民族歧视，破坏民族团结的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(e) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">破坏国家宗教政策，宣扬邪教和封建迷信的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(f) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">散布谣言，扰乱社会秩序，破坏社会稳定的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(g) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">散布淫秽、色情、赌博、暴力、恐怖或者教唆犯罪的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(h) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">侮辱或者诽谤他人，侵害他人合法权益的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(i) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">煽动非法集会、结社、游行、示威、聚众扰乱社会秩序的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(j) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">以非法民间组织名义活动的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(k) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">含有法律、行政法规禁止的其他内容的。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">2</span>）用户在锋源网络的网页上发布信息或者利用锋源网络的服务时还必须符合其他有关国家和地区的法律规定以及国际法的有关规定。用户需遵守法律法规的规定使用锋源网络微、博客服务。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">3</span>）用户不得利用锋源网络的服务从事以下活动：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(a) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">未经允许，进入计算机信息网络或者使用计算机信息网络资源的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(b) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">未经允许，对计算机信息网络功能进行删除、修改或者增加的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(c) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">未经允许，对进入计算机信息网络中存储、处理或者传输的数据和应用程序进行删除、修改或者增加的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(d) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">故意制作、传播计算机病毒等破坏性程序的；</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">(e) </span><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">其他危害计算机信息网络安全的行为。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">4</span>）用户不得以任何方式干扰锋源网络的服务。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">5</span>）用户不得滥用锋源网络服务，包括但不限于：利用锋源网络服务进行侵害他人知识产权或者合法利益的其他行为。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">6</span>）用户应遵守锋源网络的所有其他规定和程序。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">用户须对自己在使用锋源网络服务过程中的行为承担法律责任。用户承担法律责任的形式包括但不限于：对受到侵害者进行赔偿，以及在锋源网络首先承担了因用户行为导致的行政处罚或侵权损害赔偿责任后，用户应给予锋源网络等额的赔偿。若用户违反以上规定，锋源网络有权作出独立判断立即暂停或终止对用户提供部分或全部服务，包括冻结、取消用户服务帐号等措施。用户理解，如果锋源网络发现其网站传输的信息明显属于上段第<span lang="EN-US">(1)</span>条所列内容之一，依据中国法律，锋源网络有义务立即停止传输，保存有关记录，向国家有关机关报告，并且删除含有该内容的地址、目录或关闭服务器。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">用户使用锋源网络电子公告服务，包括电子布告牌、电子白板、电子论坛、网络聊天室和留言等以交互形式为上网用户提供信息发布条件的行为，也须遵守本条的规定以及锋源网络将专门发布的电子公告服务规则，上段中描述的法律后果和法律责任同样适用于电子公告服务的用户。</span></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">11.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">保障</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">用户同意保障和维护锋源网络全体成员的利益，承担由用户违反服务条款的损害补偿费用，其它人使用用户的电脑、手机、帐号而产生的费用。用户或者使用用户帐号的其他人在进行游戏过程中侵犯第三方知识产权及其他权利而导致被侵权人索赔的，由用户承担责任。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">如用户或其它网络服务提供者利用锋源网络的服务侵害他人民事权益的，应当承担侵权等法律责任。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">如用户利用锋源网络的服务实施侵权行为的，被侵权人有权通知锋源网络采取删除、屏蔽、断开链接等必要措施。锋源网络接到通知后，因自身过错若未及时采取必要措施的，按法律规定承担责任。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">12.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">通知</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">所有发给用户的通知都可通过电子邮件、常规的信件或在网站显著位置公告的方式进行传送。锋源网络将通过上述方法之一将消息传递给用户，告知他们服务条款的修改、服务变更、或其它重要事情。</span></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">13.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">内容、商标的所有权</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">锋源网络提供的内容包括但不限于：非用户上传<span lang="EN-US">/</span>提供的文字、软件、声音、相片、视频、图表等。所有这些内容均属于锋源网络，并受版权、商标、专利和其它财产所有权法律的保护。所以，用户只能在锋源网络授权下才能使用这些内容，而不能擅自复制、再造这些内容、或创造与内容有关的派生产品。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">锋源网络的其他标志及产品、服务的名称，均为锋源网络之商标（以下简称&ldquo;锋源网络标识&rdquo;）。未经锋源网络事先书面同意，您不得将锋源网络标识以任何方式展示或使用或作其他处理，也不得向他人表明您有权展示、使用、或其他有权处理锋源网络标识的行为。</span></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">14.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">法律</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">本条款适用中华人民共和国的法律，并且排除一切冲突法规定的适用。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">如使用本条款项下服务中出现纠纷的，用户与锋源网络应友好协商解决，若协商不成，用户同意将纠纷提交中国国际经济贸易仲裁委员会仲裁解决，并由<span lang="EN-US">3</span>名仲裁员进行审理。仲裁裁决是终局的，对双方均有约束力。若单项条款与本服务条款在管辖约定内容上存在冲突，则在单项条款约束范围内应以单项条款为准。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">15.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">信息储存及相关知识产权</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">锋源网络对锋源网络手机帐号上所有服务将尽力维护其安全性及方便性，但对服务中出现的信息（包括但不限于用户发布的信息）删除或储存失败不承担任何责任。另外锋源网络有权判定用户的行为是否符合本服务条款的要求，如果用户违背了本服务条款的规定，锋源网络有权中止或者终止对其锋源网络手机帐号的服务。</span></u></strong><u></u></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><u><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: black; background: white;">锋源网络尊重知识产权并注重保护用户享有的各项权利。在锋源网络手机帐号所含服务中，用户可能需要通过上传、发布等各种方式向锋源网络提供内容。在此情况下，用户仍然享有此等内容的完整知识产权。用户在提供内容时将授予锋源网络一项全球性的免费许可，允许锋源网络使用、传播、复制、修改、再许可、翻译、创建衍生作品、出版、表演及展示此等内容。</span></u></strong><u></u></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">16.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">青少年用户特别提示</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">青少年用户必须遵守全国青少年网络文明公约：</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">要善于网上学习，不浏览不良信息；要诚实友好交流，不侮辱欺诈他人；要增强自护意识，不随意约会网友；要维护网络安全，不破坏网络秩序；要有益身心健康，不沉溺虚拟时空。</span></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">17.</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">其他</span></strong></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">1</span>）锋源网络不行使、未能及时行使或者未充分行使本条款或者按照法律规定所享有的权利，不应被视为放弃该权利，也不影响锋源网络在将来行使该权利。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">2</span>）如本条款中的任何条款无论因何种原因完全或部分无效或不具有执行力，本服务条款的其余条款仍应有效且具有约束力，锋源网络及用户均应尽力使该条款设定的本意得到实现。</span></p>
<p style="text-indent: 21.0pt; line-height: 15.75pt; mso-pagination: widow-orphan; background: white;"><span style="font-size: 10.5pt; font-family: '微软雅黑','sans-serif'; mso-bidi-font-family: 微软雅黑; color: #333333; background: white;">（<span lang="EN-US">3</span>）本条款中的标题仅为方便而设，不作为解释本条款的依据。</span></p>
<p class="MsoNormal" style="text-align: left; mso-pagination: widow-orphan;" align="left"><span lang="EN-US">&nbsp;</span></p>
<p class="MsoNormal"><span lang="EN-US">&nbsp;</span></p>